# Generated by Django 5.0.6 on 2024-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='sessionid',
            field=models.CharField(default='000000000000000000000000000000', max_length=30),
        ),
    ]
