# Generated by Django 5.0.6 on 2024-07-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_newuser_sessionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newUser',
        ),
    ]
