# Generated by Django 5.0.6 on 2024-07-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='plan',
            field=models.CharField(default='starter', max_length=15),
        ),
    ]
