# Generated by Django 5.0.6 on 2024-07-17 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_apikey_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 21, 49, 59, 616763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='transactions_left',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 21, 49, 59, 616763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='plan',
            field=models.CharField(default='starter', max_length=20),
        ),
    ]
