# Generated by Django 5.0.6 on 2024-07-17 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_apikey_creation_date_apikey_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 22, 0, 48, 604310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 22, 0, 48, 604310, tzinfo=datetime.timezone.utc)),
        ),
    ]
