# Generated by Django 5.0.6 on 2024-07-17 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_apikey_creation_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 16, 22, 22, 5, 675167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 22, 22, 5, 675167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 17, 22, 22, 5, 675167, tzinfo=datetime.timezone.utc)),
        ),
    ]
