# Generated by Django 5.0.6 on 2024-07-18 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_apikey_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 18, 10, 56, 30, 328219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 17, 10, 56, 30, 328219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 18, 10, 56, 30, 328715, tzinfo=datetime.timezone.utc)),
        ),
    ]
